-- Insert additional pre-order vehicles
-- Run via: SUPABASE_PAT=sbp_xxx node scripts/insert-blog-post.mjs  (or paste into Supabase SQL Editor)

INSERT INTO vehicles (make, model, trim, year, price, currency, mileage, condition, transmission, fuel_type, colour, body_type, description, features, status, is_featured, published_at)
VALUES
  ('Mercedes-Benz', 'GLE 350 de', 'AMG Line', 2024, 88000000, 'NGN', 0, 'new', 'automatic', 'plug-in-hybrid', 'Selenite Grey', 'suv', '2024 Mercedes-Benz GLE 350 de with AMG Line package — plug-in hybrid combining electric city driving with diesel range for long Nigerian road trips.', '["AMG Line Package","Plug-In Hybrid","MBUX Infotainment","Panoramic Roof","Air Suspension"]'::jsonb, 'pre-order', false, now()),
  ('Mercedes-Benz', 'GLC 300', '4MATIC', 2024, 72000000, 'NGN', 0, 'new', 'automatic', 'petrol', 'Obsidian Black', 'suv', 'The new-generation 2024 Mercedes-Benz GLC 300 4MATIC — a mid-size SUV with the latest MBUX, 48V mild hybrid, and a refined cabin.', '["4MATIC AWD","MBUX","48V Mild Hybrid","Burmester Sound","Adaptive Suspension"]'::jsonb, 'pre-order', false, now()),
  ('Mercedes-Benz', 'S 500', 'Long', 2023, 145000000, 'NGN', 15000, 'used', 'automatic', 'petrol', 'Nautical Blue', 'sedan', 'Flagship 2023 Mercedes-Benz S 500 Long with the full suite of luxury — rear entertainment, massaging seats, and adaptive magic body control.', '["Magic Body Control","Rear Entertainment","Massage Seats","Burmester 4D","Air Balance"]'::jsonb, 'pre-order', true, now()),
  ('BMW', 'X7', 'xDrive40i', 2024, 120000000, 'NGN', 0, 'new', 'automatic', 'petrol', 'Mineral White', 'suv', 'Full-size 2024 BMW X7 xDrive40i with seven seats, panoramic sky lounge, and the commanding presence that fits executives and large families alike.', '["Seven Seats","Panoramic Sky Lounge","Bowers & Wilkins","Adaptive M Suspension","iDrive 8"]'::jsonb, 'pre-order', false, now()),
  ('BMW', '330i', 'M Sport', 2024, 52000000, 'NGN', 0, 'new', 'automatic', 'petrol', 'Portimao Blue', 'sedan', 'The 2024 BMW 330i M Sport — sporty executive saloon with a turbocharged 2.0L, sharp handling, and the latest iDrive 8 infotainment.', '["M Sport Package","Turbocharged 2.0L","iDrive 8","Harman Kardon","Laser Lights"]'::jsonb, 'pre-order', false, now()),
  ('Toyota', 'Land Cruiser Prado', 'TX', 2024, 95000000, 'NGN', 0, 'new', 'automatic', 'petrol', 'White Pearl', 'suv', 'The legendary 2024 Toyota Land Cruiser Prado TX — rugged, reliable, and built for any road. A favourite for families and fleet operators.', '["4WD","Third Row","Toyota Safety Sense","Ventilated Seats","Multimedia Display"]'::jsonb, 'pre-order', true, now()),
  ('Toyota', 'Highlander', 'Limited', 2024, 62000000, 'NGN', 0, 'new', 'automatic', 'hybrid', 'Celestial Silver', 'suv', '2024 Toyota Highlander Limited hybrid — a spacious three-row SUV with impressive fuel economy and a quiet, comfortable ride.', '["Hybrid Powertrain","Three Rows","Toyota Safety Sense","Panoramic Roof","Wireless CarPlay"]'::jsonb, 'pre-order', false, now()),
  ('Lexus', 'RX 450h', 'Luxury', 2024, 78000000, 'NGN', 0, 'new', 'automatic', 'hybrid', 'Sonic Titanium', 'suv', 'The refined 2024 Lexus RX 450h Luxury — hybrid efficiency wrapped in Lexus craftsmanship with Mark Levinson audio.', '["Hybrid Powertrain","Mark Levinson Audio","Lexus Safety System+","Adaptive Variable Suspension","Heated & Ventilated Seats"]'::jsonb, 'pre-order', false, now()),
  ('Lexus', 'ES 350', 'Luxury', 2024, 58000000, 'NGN', 0, 'new', 'automatic', 'petrol', 'Eminent White', 'sedan', 'The 2024 Lexus ES 350 Luxury — a plush, quiet executive saloon with the reliability Lexus is known for.', '["Mark Levinson Audio","Lexus Safety System+","Paddle Shifters","Premium Leather","Ambient Lighting"]'::jsonb, 'pre-order', false, now()),
  ('Range Rover', 'Sport', 'Dynamic SE', 2024, 210000000, 'NGN', 0, 'new', 'automatic', 'petrol', 'Eiger Grey', 'suv', '2024 Range Rover Sport Dynamic SE — commanding luxury SUV with air suspension, dual-screen Pivi Pro, and go-anywhere capability.', '["Air Suspension","Pivi Pro Dual Screen","Meridian Sound","Terrain Response 2","Panoramic Roof"]'::jsonb, 'pre-order', true, now()),
  ('Audi', 'Q7', '55 TFSI', 2023, 98000000, 'NGN', 12000, 'used', 'automatic', 'petrol', 'Navarra Blue', 'suv', '2023 Audi Q7 55 TFSI — a premium seven-seat SUV with quattro all-wheel drive and a refined, tech-forward cabin.', '["quattro AWD","Seven Seats","Virtual Cockpit","Bang & Olufsen","Adaptive Air Suspension"]'::jsonb, 'pre-order', false, now()),
  ('Porsche', 'Cayenne', 'E-Hybrid', 2023, 145000000, 'NGN', 9000, 'used', 'automatic', 'plug-in-hybrid', 'Carrara White', 'suv', '2023 Porsche Cayenne E-Hybrid — sporty plug-in hybrid SUV blending performance with electric city driving.', '["Plug-In Hybrid","Sport Chrono","Air Suspension","Burmester 3D","Matrix LED"]'::jsonb, 'pre-order', true, now());

-- Add a cover image for each pre-order vehicle just inserted
INSERT INTO vehicle_media (vehicle_id, type, url, sort_order, is_primary, alt_text)
SELECT id, 'image', 'https://images.unsplash.com/photo-1636578929419-fc62088fd08f?w=800&h=600&fit=crop', 0, true, make || ' ' || model
FROM vehicles WHERE status = 'pre-order' AND NOT EXISTS (
  SELECT 1 FROM vehicle_media vm WHERE vm.vehicle_id = vehicles.id
);

SELECT 'PRE-ORDER VEHICLES' AS table_name, COUNT(*) AS count FROM vehicles WHERE status = 'pre-order';
